"""LIBERO-YAM connector glue: cuRobo IK backend + object-pose tool + factory.

IK uses cuRobo (the version installed in this venv, v0.8) built from LIBERO-YAM's
own ``assets/curobo_configs/yam.yml`` — the same robot config its
``scripts/yam_ik.py`` uses (joint names, retract pose, cspace weights), with the
three v0.7→v0.8 field renames applied in ``_yam_robot_cfg``. The connector's
``robot.go_to_pose`` calls ``backend.solve_ik(world_pose)``; we transform world→
base (YAM bases are mounted upright → translation only), subtract the TCP offset
to target link_6, and solve on the GPU. Dynamics stay 100% LIBERO-YAM (the env
steps ``ControlEnv``); cuRobo only computes joint targets.

(``yam_ik.py`` itself can't be imported here: it targets the classic cuRobo v0.7
``IKSolver`` API, which v0.8 dropped — and v0.7 can't coexist with the v0.8
install gap is pinned to. So we reuse its *config*, ported to the v0.8 solver.)

    import gap
    conn = gap.connector.libero_yam(bddl=".../two_tape_handover.bddl")
    gap.execute("examples/tape_handover_yam", conn, skills=[".../tsh-skills"])
"""

from __future__ import annotations

from copy import deepcopy
from pathlib import Path
from typing import Any

import numpy as np
import yaml
from scipy.spatial.transform import Rotation

from gap.connector.sim import SimConnector
from gap.envs.libero_yam_env import YAM_TCP_OFFSET
from gap_core.tools import ToolRegistry


# Stream every Nth interpolated curobo waypoint in _execute_plan (each played one
# 30 Hz sim step). 2 roughly halves transit time vs streaming all waypoints; the
# final waypoint is always executed + converged so end-pose accuracy is unchanged.
_EXEC_WAYPOINT_STRIDE = 2

# Finger joint's fully-open value (URDF `left_finger` prismatic upper limit).
# yam.yml locks the finger CLOSED; we lock it OPEN instead (see _yam_robot_cfg)
# so the collision model always over-approximates the finger footprint.
_FINGER_OPEN_QPOS = 0.0475


def _yam_assets() -> Path:
    ### take EVERYTHING from LIBERO-YAM repo
    import libero_yam

    return Path(libero_yam.__file__).resolve().parent / "assets"


def _yam_robot_cfg(with_collision_spheres: bool = True):
    """Build a cuRobo-0.8 ``RobotCfg`` from LIBERO-YAM's own ``yam.yml``.

    Reuses the repo's curated robot config (joint names, retract pose, cspace
    weights, accel/jerk limits) rather than deriving everything from the bare
    URDF, so this matches LIBERO-YAM's ``scripts/yam_ik.py`` as closely as the
    installed cuRobo allows. ``yam.yml`` is written for cuRobo v0.7, so three
    fields are translated to the v0.8 loader schema:
      * drop ``use_usd_kinematics`` (no longer a loader field);
      * ``ee_link`` (str) -> ``tool_frames`` (list);
      * ``cspace.retract_config`` -> ``cspace.default_joint_position``.
    Relative URDF/asset paths are made absolute.

    Collision spheres for self- and arm-arm collision avoidance are not in
    ``yam.yml``; when ``with_collision_spheres`` and ``yam_spheres.yml`` exists
    (generated by fitting the per-link collision STLs, cuRoboV2 App. A.1.2), its
    ``collision_spheres`` / ``self_collision_*`` fields are merged in so the
    planner has a body model. IK still solves with ``self_collision_check=False``
    so the extra fields are inert there.
    """
    from curobo._src.types.robot import RobotCfg

    assets = _yam_assets()
    urdf_dir = assets / "sim_models" / "i2rt_yam" / "urdf"
    ### load yaml file
    cfg = yaml.safe_load((assets / "curobo_configs" / "yam.yml").read_text())
    kin = deepcopy(cfg["robot_cfg"]["kinematics"])
    kin.pop("use_usd_kinematics", None)
    ee = kin.pop("ee_link", None)
    if ee is not None:
        kin["tool_frames"] = [ee]
    kin["urdf_path"] = str(urdf_dir / "yam.urdf")
    kin["asset_root_path"] = str(urdf_dir)
    # yam.yml locks the finger CLOSED (0.0); the locked value is baked into the
    # planner's FK at construction and does not track the live gripper state
    # (cuRobo's update_kinematics_config updates KinematicsParams.lock_jointstate
    # but does not recompute the cached fixed_transforms FK reads from, so a
    # locked value is only ever as fresh as the last MotionPlanner rebuild).
    # Lock OPEN instead, so the collision model always over-approximates the
    # finger footprint rather than under-approximating it during bimanual
    # close-quarters planning -- the standard conservative default (matches
    # upstream cuRobo's own franka.yml, which locks panda fingers open).
    lock = kin.get("lock_joints")
    if isinstance(lock, dict) and "left_finger" in lock:
        lock["left_finger"] = _FINGER_OPEN_QPOS
    cs = kin.get("cspace")
    if isinstance(cs, dict) and "retract_config" in cs:
        cs["default_joint_position"] = cs.pop("retract_config")

    spheres_path = assets / "curobo_configs" / "yam_spheres.yml"
    has_spheres = with_collision_spheres and spheres_path.exists()
    if has_spheres:
        kin.update(yaml.safe_load(spheres_path.read_text()))
    return RobotCfg.create(
        {"robot_cfg": {"kinematics": kin}}, load_collision_spheres=has_spheres,
    )


class LiberoYamCuRoboIK:
    """IK backend (connector contract) over cuRobo v0.8, built from the YAM URDF."""

    def __init__(self, env: Any, *, num_seeds: int = 64) -> None:
        self._env = env  # LiberoYamEnv
        self._num_seeds = int(num_seeds)
        self._ik = None  # lazy: cuRobo solver builds on first solve (needs CUDA)
        self._link = None
        self._planner = None  # lazy: collision-aware MotionPlanner (plan_to_pose)
        self._planner_link = None

    @property
    def trajectory_needs_joint_reverse(self) -> bool:
        return False  # cuRobo reports natural joint1..6 order (sim-native)

    def _solver(self):
        if self._ik is None:
            from curobo.inverse_kinematics import InverseKinematics, InverseKinematicsCfg

            robot_cfg = _yam_robot_cfg()
            cfg = InverseKinematicsCfg.create(
                robot=robot_cfg, num_seeds=self._num_seeds,
                position_tolerance=0.01, orientation_tolerance=0.05,
                self_collision_check=False,
                # CUDA-graph capture conflicts with MuJoCo's EGL CUDA usage in
                # the same process; disable it (small per-solve cost).
                use_cuda_graph=False,
            )
            self._ik = InverseKinematics(cfg)
            self._link = self._ik.tool_frames[0]
        return self._ik

    def solve_ik(self, pose, *, arm_id=0, seed_joints=None, tcp_offset=None):
        import torch
        from curobo.types import GoalToolPose, JointState, Pose

        from libero_yam.sim.kinematics import arm_base_world_pose

        ik = self._solver()
        base_pos, _ = arm_base_world_pose(self._env._control, arm_id)
        p, q = pose["position"], pose["rotation"]
        quat_wxyz = np.array([q["w"], q["x"], q["y"], q["z"]], dtype=np.float64)

        # world TCP -> arm-base frame -> link_6 (subtract the TCP offset).
        rel = np.array([p["x"], p["y"], p["z"]], dtype=np.float64) - np.asarray(base_pos)
        R = Rotation.from_quat([q["x"], q["y"], q["z"], q["w"]]).as_matrix()
        link6 = rel - R @ np.asarray(YAM_TCP_OFFSET, dtype=np.float64)

        goal = Pose(
            position=torch.tensor([link6], device="cuda", dtype=torch.float32),
            quaternion=torch.tensor([quat_wxyz], device="cuda", dtype=torch.float32),
        )

        # Seed the solver with the current arm configuration so cuRobo biases
        # toward the nearest solution branch rather than picking arbitrarily
        # from 64 random seeds. Without this, consecutive calls for nearby
        # poses can return configurations on opposite IK branches (e.g.
        # elbow-up vs elbow-down), forcing the arm across large joint-space
        # distances and causing the jitter seen in the video.
        current_state = None
        if seed_joints is not None:
            q_seed = torch.tensor(
                [list(seed_joints[:6])], device="cuda", dtype=torch.float32
            )
            current_state = JointState.from_position(q_seed)

        # cuRobo v0.8 can raise (empty cost list) on far/unreachable targets
        # instead of reporting failure — treat any failure as "no IK solution".
        # It can also raise torch.cat() on an empty tensor list when
        # current_state (seed) is provided; retry without the seed in that case.
        def _attempt(state):
            try:
                res = ik.solve_pose(
                    GoalToolPose.from_poses({self._link: goal}, num_goalset=1),
                    current_state=state,
                )
                return res if bool(res.success.any().item()) else None
            except Exception:
                return False  # sentinel: exception (distinct from None=infeasible)

        res = _attempt(current_state)
        if res is False:
            # cuRobo throws torch.cat() when the seed tensor conflicts with its
            # internal batch shape — retry without seed (pure 64 random seeds).
            res = _attempt(None)
        if res is None or res is False:
            return None
        sol = res.js_solution.position.detach().cpu().numpy().reshape(-1)[:6]  # type: ignore[union-attr]
        return [float(v) for v in sol]

    # ------------------------------------------------------------------
    # Collision-aware planning (cuRobo v0.8 MotionPlanner)
    # ------------------------------------------------------------------
    def _motion_planner(self):
        """Lazily build a collision-aware MotionPlanner from the YAM RobotCfg.

        Reuses ``_yam_robot_cfg`` (same config as solve_ik) with an ``obb``
        collision cache so cuboid obstacles can be loaded via ``update_world``.
        CUDA-graph capture is disabled (it conflicts with MuJoCo's in-process
        EGL CUDA use, same as the IK solver). Mesh cache is left unallocated —
        the installed warp build errors on mesh-cache creation, and the YAM
        scene is modelled with oriented boxes (obb) anyway.
        """
        if self._planner is None:
            from curobo.motion_planner import MotionPlanner, MotionPlannerCfg

            cfg = MotionPlannerCfg.create(
                robot=_yam_robot_cfg(),
                self_collision_check=True,
                # obb cache must hold the other arm's whole sphere cloud (each
                # sphere is injected as one cuboid by _other_arm_obstacles). The
                # arm is ~108 spheres now that the fingers are fit to their real
                # geometry, so 64 would overflow and silently drop obstacles.
                collision_cache={"obb": 128},
                num_ik_seeds=32,
                position_tolerance=0.005,
                orientation_tolerance=0.05,
                use_cuda_graph=False,
            )
            self._planner = MotionPlanner(cfg)
            self._planner_link = self._planner.tool_frames[0]
        return self._planner

    def _load_world(self, planner, obstacles, base_pos):
        """Push world-frame cuboid ``obstacles`` into ``planner`` (base frame).

        YAM bases are mounted upright (world-aligned), so world->base is a pure
        translation — subtract ``base_pos`` from each obstacle centre and keep
        its orientation. Each obstacle is
        ``{"name", "center": (x,y,z), "dims": (dx,dy,dz), "quat_wxyz"?}`` with
        ``dims`` the FULL box extents in metres.
        """
        from curobo._src.geom.types import SceneCfg
        from curobo.scene import Cuboid

        cuboids = []
        for i, ob in enumerate(obstacles or []):
            cx, cy, cz = ob["center"]
            qw, qx, qy, qz = ob.get("quat_wxyz", (1.0, 0.0, 0.0, 0.0))
            cuboids.append(Cuboid(
                name=ob.get("name", f"obs_{i}"),
                pose=[cx - base_pos[0], cy - base_pos[1], cz - base_pos[2],
                      qw, qx, qy, qz],
                dims=list(ob["dims"]),
            ))
        planner.clear_scene_cache()
        planner.update_world(SceneCfg(cuboid=cuboids))

    def _other_arm_obstacles(self, planning_arm_id):
        """World-frame cuboids covering the OTHER arm at its current config.

        The cuRobo scene checker only ingests cuboids/mesh/voxel (spheres are
        silently dropped) and meshes are broken on this warp build, so the other
        arm's collision spheres (from FK) are each emitted as a cube (side 2r) —
        tighter than per-link boxes and enough to make the planning arm route
        around the giver during the handover. Rebuilt each plan from the other
        arm's live joints, so it tracks wherever that arm currently is.
        """
        from libero_yam.sim.kinematics import arm_base_world_pose

        other = 1 - planning_arm_id
        obs = self._env.get_observation().get(f"robot_joint_pos_{other}")
        if obs is None:
            return []
        q = np.asarray(obs[:6], dtype=np.float32)
        grip_frac = float(obs[6]) if len(obs) > 6 else 0.0
        grip_qpos = grip_frac * _FINGER_OPEN_QPOS
        planner = self._motion_planner()
        from curobo._src.state.state_joint import JointState
        ss = JointState.from_numpy(
            joint_names=planner.joint_names, position=q[None],
            device_cfg=planner.config.device_cfg)
        kin_state = planner.compute_kinematics(ss)
        spheres = kin_state.robot_spheres.reshape(-1, 4).cpu().numpy()
        n_sph = spheres.shape[0]
        n_finger = 6
        # FK bakes the fingers at the LOCKED (open) pose (see _yam_robot_cfg),
        # so the slide is relative to that baseline, not zero: at grip_frac=1
        # (open) slide=0 (already correct from FK); at grip_frac=0 (closed)
        # slide=-_FINGER_OPEN_QPOS, pulling the spheres back in to closed.
        slide = grip_qpos - _FINGER_OPEN_QPOS
        if slide != 0.0 and n_sph >= 2 * n_finger and kin_state.tool_poses is not None:
            ee_quat_wxyz = kin_state.tool_poses.quaternion.reshape(4).cpu().numpy()
            q_xyzw = [ee_quat_wxyz[1], ee_quat_wxyz[2], ee_quat_wxyz[3], ee_quat_wxyz[0]]
            R6 = Rotation.from_quat(q_xyzw).as_matrix()
            slide_dir = R6[:, 0]
            spheres[n_sph - 2 * n_finger:n_sph - n_finger, :3] += slide * slide_dir
            spheres[n_sph - n_finger:n_sph, :3] -= slide * slide_dir
        base = np.asarray(arm_base_world_pose(self._env._control, other)[0])
        out = []
        for i, (x, y, z, r) in enumerate(spheres):
            if r <= 0:
                continue
            out.append({"name": f"otherarm_{i}",
                        "center": (float(x) + base[0], float(y) + base[1], float(z) + base[2]),
                        "dims": (2 * float(r), 2 * float(r), 2 * float(r))})
        return out

    def plan_to_pose(self, pose, *, arm_id=0, obstacles=None, avoid_other_arm=False,
                     seed_joints=None, max_attempts=4):
        """Collision-aware joint trajectory to a world-frame TCP ``pose``.

        Mirrors ``solve_ik``'s world->base->link_6 transform, loads ``obstacles``
        (plus the other arm as cuboids when ``avoid_other_arm``) as the collision
        world, and runs cuRobo's MotionPlanner. Returns a gap ``Trajectory`` dict
        (``{"waypoints": [{"positions": [...6...]}]}``) of joint waypoints, or
        ``None`` if planning fails. All frames are relative to the arm base, so
        the plan generalises across tape positions.
        """
        import torch
        from curobo._src.state.state_joint import JointState
        from curobo._src.types.pose import Pose
        from curobo._src.types.tool_pose import GoalToolPose

        from libero_yam.sim.kinematics import arm_base_world_pose

        planner = self._motion_planner()
        base_pos, _ = arm_base_world_pose(self._env._control, arm_id)
        base_pos = np.asarray(base_pos)

        world_obstacles = list(obstacles or [])
        if avoid_other_arm:
            world_obstacles += self._other_arm_obstacles(arm_id)

        # world TCP -> arm-base frame -> link_6 target (same as solve_ik).
        p, q = pose["position"], pose["rotation"]
        quat_wxyz = np.array([q["w"], q["x"], q["y"], q["z"]], dtype=np.float32)
        rel = np.array([p["x"], p["y"], p["z"]], dtype=np.float64) - base_pos
        R = Rotation.from_quat([q["x"], q["y"], q["z"], q["w"]]).as_matrix()
        link6 = (rel - R @ np.asarray(YAM_TCP_OFFSET, dtype=np.float64)).astype(np.float32)

        self._load_world(planner, world_obstacles, base_pos)
        planner.reset_seed() ### why are we reseting the seed every plan? this prevents warm start

        device_cfg = planner.config.device_cfg
        seed = seed_joints if seed_joints is not None else [0.0, 1.5, 1.5, 0.0, 0.0, 0.0]
        start = JointState.from_numpy(
            joint_names=planner.joint_names,
            position=np.asarray(seed[:6], dtype=np.float32)[None],
            device_cfg=device_cfg,
        )
        goal = Pose(
            position=torch.tensor(link6[None], device="cuda", dtype=torch.float32),
            quaternion=torch.tensor(quat_wxyz[None], device="cuda", dtype=torch.float32),
            name=self._planner_link,
        )
        result = planner.plan_pose(
            GoalToolPose.from_poses({self._planner_link: goal}, num_goalset=1),
            start, max_attempts=max_attempts,
        )
        if result is None or not bool(result.success.any().item()):
            return None
        traj = result.get_interpolated_plan().position.detach().cpu().numpy().reshape(-1, 6)
        return {"waypoints": [{"positions": [float(v) for v in wp]} for wp in traj]}


class LiberoYamSimConnector(SimConnector):
    """SimConnector that exposes ``libero-yam.object_pose`` (ground-truth object pose)."""

    def world_snapshot(self):
        """Base ``world_snapshot`` with YAM robot-link prefixes.

        The YAM MJCF names every arm/gripper body ``left_*`` / ``right_*``
        (link_1..6, *_lf/rf finger bodies) — none match the adapter's default
        Panda-era prefixes, so contacts with the fingers would not register
        as robot contacts and ``Body.is_grasped()`` would always be False in
        checkpoint predicates. Same lazy-build shape as the base method.
        """
        if self._world_adapter is None:
            from gap.connector.world_adapter import LiberoWorldAdapter

            self._world_adapter = LiberoWorldAdapter(
                self.env, robot_link_prefixes=("left_", "right_"), arm_dof=6)
        return self._world_adapter.snapshot()

    def get_observation(self):
        """Same as the base observation, but attach RGB-D camera frames.

        Cameras are rendered here (on the ``robot.get_observation`` tool call),
        NOT on the env's per-step get_observation() — perception is only needed
        at the grasp instant, so the step loop stays render-free. No-op when no
        perception cameras were configured.
        """
        obs = self.env.get_observation()
        obs.update(self.env.camera_frames())
        return self._build_observation(obs)

    def open_gripper(self, settle_steps: int = 10, arm_id: int = 0,
                     fraction: float = 1.0) -> dict:
        """Open the gripper to ``fraction`` (0 = closed, 1 = fully open).

        A partial open (e.g. 0.5) releases the held object without spreading
        the fingers wide enough to collide with a nearby arm during a bimanual
        exchange.
        """
        settle = settle_steps if settle_steps > 0 else 10
        self.set_gripper(float(fraction), arm_id=arm_id)
        for _ in range(settle):
            self.step_once()
        position = self.get_gripper_fraction(arm_id=arm_id)
        return {"position": position}

    def close_gripper(self, settle_steps: int = 20, arm_id: int = 0,
                      ramp_steps: int = 0) -> dict:
        """Close the gripper, optionally ramping the jaws shut for a gentler grasp.

        ``ramp_steps`` > 0 steps the commanded open-fraction linearly from its
        current value to 0 over that many sim steps, so the YAM jaws close slowly
        instead of snapping under the stiff (kp=800) PD. The base settle loop then
        holds fully closed for the remaining ``settle_steps - ramp_steps`` steps,
        so total dwell is unchanged. ramp_steps=0 (default) is the base snap-close
        verbatim — this override only adds behaviour for the YAM connector; every
        other connector (Franka sim, real) keeps the unchanged base method.
        """
        ramp = max(0, min(ramp_steps, settle_steps))
        if ramp > 0:
            start = self.get_gripper_fraction(arm_id=arm_id)
            for i in range(1, ramp + 1):
                self.set_gripper(start * (1.0 - i / ramp), arm_id=arm_id)
                self.step_once()
        return super().close_gripper(
            settle_steps=max(1, settle_steps - ramp), arm_id=arm_id)

    def _register_extra_tools(self, reg: ToolRegistry) -> None:
        super()._register_extra_tools(reg)
        reg.register_callable(
            "libero-yam.object_pose",
            self.env.get_object_pose,
            summary="World-frame pose of a scene object by body name.",
        )
        reg.register_callable(
            "robot.plan_move",
            self._plan_move,
            summary="Collision-aware cuRobo plan to a world TCP pose (optionally "
                    "avoiding the other arm), then stream-execute the trajectory.",
        )
        reg.register_callable(
            "libero-yam.arm_base_pose",
            self._arm_base_pose,
            summary="Arm base world pose + TCP offset + current joints — the frame "
                    "info a skill needs to plan for this arm via curobo.plan_to_pose.",
        )
        reg.register_callable(
            "libero-yam.execute_trajectory",
            self._execute_plan,
            summary="Stream-execute a cuRobo joint Trajectory (from curobo.plan_to_pose) "
                    "on the given arm, PD-controlled so the grasp descent respects "
                    "contact (unlike the core closed-loop robot.execute_trajectory).",
        )

    def _plan_move(self, pose, arm_id: int = 0, avoid_other_arm: bool = False,
                   max_steps: int = 200) -> dict:
        """Plan a collision-aware trajectory and execute it smoothly.

        Streams the dense trajopt waypoints one sim step each (nonblocking
        publish), then a single blocking converge on the final pose — the YAM
        env has no ``stream_joint_trajectory`` so per-waypoint blocking would
        stop-start. Raises ``ToolError`` when planning fails (unreachable /
        no collision-free path).
        """
        from gap_core.errors import ToolError

        traj = self.ik.plan_to_pose(
            pose, arm_id=arm_id, avoid_other_arm=avoid_other_arm,
            seed_joints=self._current_joints(arm_id),
        )
        if traj is None:
            raise ToolError("robot.plan_move", "no collision-free plan found")
        wps = traj["waypoints"]
        for wp in wps[:-1]:
            self.move_to_joints(wp["positions"], max_steps=0, arm_id=arm_id)
        self.move_to_joints(
            wps[-1]["positions"], tolerance=0.03, max_steps=max_steps, arm_id=arm_id)
        return {"planned": True, "waypoints": len(wps)}

    def _arm_base_pose(self, arm_id: int = 0) -> dict:
        """Frame info for planning this arm with the canonical curobo bundle.

        Returns the arm's base world pose, the fixed link_6->TCP offset, and the
        arm's current joints — everything a skill needs to (a) convert a world
        TCP target into the arm-base frame cuRobo plans in, (b) pass the TCP
        offset so the fingertip (not link_6) lands on the target, and (c) seed
        ``start_joint_position``. YAM bases are mounted upright (world-aligned),
        so a world->base transform is a pure translation by ``position``.
        """
        from libero_yam.sim.kinematics import arm_base_world_pose

        base_pos, base_quat = arm_base_world_pose(self.env._control, arm_id)
        return {
            "position": [float(v) for v in base_pos],
            "rotation": [float(v) for v in base_quat],  # wxyz
            "tcp_offset": [float(v) for v in YAM_TCP_OFFSET],
            "joints": self._current_joints(arm_id) or [],
        }

    def _execute_plan(self, trajectory: dict, arm_id: int = 0,
                      max_steps: int = 22) -> dict:
        """Stream-execute a cuRobo joint ``Trajectory`` on the given arm.

        The canonical ``curobo.plan_to_pose`` tool only plans; this runs the
        returned joint waypoints on the sim the same way ``_plan_move`` executed
        the connector's own plan: dense waypoints streamed one sim step each
        (nonblocking), then a single blocking converge on the final waypoint.
        This is PD-controlled (contact-respecting) — distinct from the core
        ``robot.execute_trajectory``, which qpos-teleports in closed-loop mode
        and would phase the fingers through the tape on the grasp descent.
        """
        from gap_core.errors import ToolError

        wps = (trajectory or {}).get("waypoints") or []
        if not wps:
            raise ToolError("libero-yam.execute_trajectory", "trajectory has no waypoints")
        # Stream every _EXEC_WAYPOINT_STRIDE-th interpolated waypoint (each one sim
        # step): the curobo bundle interpolates at 1/15 s but the sim steps at 30 Hz,
        # so playing every waypoint already runs 2x the planned speed; striding by 2
        # runs ~4x, roughly halving transit time. The final waypoint is always
        # streamed and then blocking-converged, so end-pose accuracy is unchanged.
        for wp in wps[:-1:_EXEC_WAYPOINT_STRIDE]:
            self.move_to_joints(wp["positions"], max_steps=0, arm_id=arm_id)
        self.move_to_joints(
            wps[-1]["positions"], tolerance=0.03, max_steps=max_steps, arm_id=arm_id,
            settle_steps=3)
        return {"executed": True, "waypoints": len(wps)}


def libero_yam(
    task: Any = "libero_yam_tabletop/0",
    *,
    bddl: str | None = None,
    cameras: list[str] | None = None,
    **kw: Any,
) -> LiberoYamSimConnector:
    """Build a :class:`LiberoYamSimConnector` (cuRobo IK + libero-yam.object_pose).

    Builds the env directly from ``libero_yam_env.make_env`` and wraps it in
    ``LiberoYamSimConnector`` — no modifications to the core gap engine needed.
    """
    if cameras is None:
        cameras = ["agentview", "left", "right"]
    import os
    if "GAP_CUROBO_ROBOT_CONFIGS" not in os.environ:
        yam_cfg = _yam_assets() / "curobo_configs" / "yam.yml"
        if yam_cfg.exists():
            os.environ["GAP_CUROBO_ROBOT_CONFIGS"] = f"yam.yml={yam_cfg}"
    from gap.envs.libero_yam_env import make_env
    suite_name = task.rpartition("/")[0] if isinstance(task, str) and "/" in task else "libero_yam_tabletop"
    task_id = int(task.rpartition("/")[2]) if isinstance(task, str) and "/" in task else (int(task) if isinstance(task, int) else 0)
    env_obj, config = make_env(
        suite_name, task_id, camera_names=cameras, enable_render=True,
        **({"bddl_file": bddl} if bddl else {}), **kw,
    )
    return LiberoYamSimConnector(
        env_obj, config, camera_names=cameras,
        ik=LiberoYamCuRoboIK(env_obj),
    )
