"""Portable privileged-scene provider contract.

The connector boundary, rather than a skill, owns simulator vocabulary.
MuJoCo bodies/geoms/joints, Isaac prims and SAPIEN articulations are backend
 details. Providers expose the same concepts to ``sim.*`` tools. A third-party
provider only needs numpy arrays and dicts.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

import numpy as np


@runtime_checkable
class PrivilegedSceneAdapter(Protocol):
    """Provider surface consumed by privileged scene tools.

    Object state and ``snapshot`` form the core contract. Feature,
    articulation and contact access are capability methods: tools report an
    explicit unsupported error when a provider cannot supply one.
    """

    def reference_frame_name(self) -> str: ...
    def snapshot(self, env_id: int = 0) -> Any: ...
    def object_names(self) -> list[str]: ...
    def task_object_names(self) -> list[str]: ...
    def movable_object_names(self) -> list[str]: ...
    def part_names(self, root: str) -> list[str]: ...
    def object_pose(self, name: str) -> tuple[np.ndarray, np.ndarray] | None: ...
    def object_box(
        self, name: str,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray] | None: ...
    def feature_names(self, root: str) -> list[str]: ...
    def feature_box(
        self, root: str, feature: str,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray] | None: ...
    def articulation_names(self, root: str | None = None) -> list[str]: ...
    def articulation_state(self, name: str) -> dict[str, Any] | None: ...
    def contact_pairs(self) -> list[tuple[str, str]]: ...
    def collision_feature_contact_pairs(self) -> list[tuple[str, str]]: ...
    def named_frame_pose(
        self, name: str,
    ) -> tuple[np.ndarray, np.ndarray] | None: ...
    def workspace_surface_box(
        self,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray] | None: ...


__all__ = ["PrivilegedSceneAdapter"]
