#!/usr/bin/env python3
"""Regenerate the agent skill's CLI reference from the live parser.

Usage (from the repo root)::

    uv run python agent/scripts/gen_cli_reference.py

Writes ``agent/skills/gap/references/cli.md`` from ``gap --help`` plus
every subcommand's (and sub-subcommand's) ``--help``, rendered at a
fixed width so the output is deterministic. The committed file is pinned
by ``tests/agent_skill/test_cli_reference_fresh.py`` — touch the CLI,
re-run this script.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

os.environ["COLUMNS"] = "100"  # deterministic help-text wrapping

HEADER = """\
# GaP CLI reference

> GENERATED by `agent/scripts/gen_cli_reference.py` — do not edit by hand.
> Ground truth is always `gap <command> --help` in your checkout.

"""


def _subparsers(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return dict(action.choices)
    return {}


def render() -> str:
    from gap.cli import build_parser

    parser = build_parser()
    parts = [HEADER]
    parts.append("## gap\n\n```text\n" + parser.format_help().rstrip() + "\n```\n")
    for name, sub in _subparsers(parser).items():
        parts.append(
            f"\n## gap {name}\n\n```text\n" + sub.format_help().rstrip() + "\n```\n"
        )
        for sub_name, sub_sub in _subparsers(sub).items():
            parts.append(
                f"\n### gap {name} {sub_name}\n\n```text\n"
                + sub_sub.format_help().rstrip() + "\n```\n"
            )
    return "".join(parts)


def main() -> int:
    out = Path(__file__).resolve().parents[1] / "skills" / "gap" / "references" / "cli.md"
    content = render()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    print(f"wrote {out} ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
