"""Codegen prompts must carry a complete, *code-generated* interface reference.

The subgraph_agent / coder prompts used to describe gap.types and the builder
API with hand-curated tables in the shared include docs. Those drifted and
covered only a subset of the types, so the generators hallucinated field names
(`Se3Pose["orientation"]`, invented keys) and builder kwargs. The prompt now
injects:

  * a full gap.types field reference generated from ``gap.schema`` (every
    registered type, exact key names, nesting), and
  * the authoritative ``gap.builder.Subgraph`` API introspected from the class.

These tests guard against (a) a type silently going undocumented and (b) the
rotation/orientation class of field-name drift, and pin the scope split
(builder API → subgraph_agent only; type reference → both generators).
"""

from __future__ import annotations

import pytest

from gap.agent._catalog import load_codegen_registries
from gap.agent._registry import default_agent_registry
from gap.agent.prompt_assembler import PromptAssembler

GENERATED_SPEC = {
    "name": "measure",
    "description": "count widgets",
    "inputs": {},
    "outputs": {"count": "int"},
    "exit": {"router_field": None, "success_values": ["measured"]},
    "on_error": "failed",
    "generated": True,
}

REGISTERED_SPEC = {
    "name": "perceive",
    "description": "perceive the target",
    "inputs": {},
    "outputs": {"target_obb": "OrientedBoundingBox"},
    "exit": {"router_field": None, "success_values": ["found"]},
    "on_error": "not_found",
}

CODER_SPEC = {
    "name": "compute_align_pose",
    "signature": "def run(ctx, obb: OrientedBoundingBox) -> Output",
    "purpose": "compute an aligned grasp pose",
    "subgraph_name": "grasp",
}


@pytest.fixture
def assembler(skills_root):
    skills, tools = load_codegen_registries(skills_root)
    return PromptAssembler(default_agent_registry(), skills, tools)


class TestTypeReference:
    def test_every_registry_type_documented(self, assembler):
        """Anti-drift: the reference is generated by iterating TYPE_REGISTRY, so
        every registered name (primary or alias) must appear. A future
        gap.types type can never silently go undocumented."""
        from gap_core.schema import TYPE_REGISTRY

        ref = assembler._render_type_reference()
        for name in TYPE_REGISTRY:
            assert name in ref, f"type {name!r} missing from generated reference"

    def test_previously_undocumented_types_present(self, assembler):
        # These were absent from the old hand table; now documented as headers.
        ref = assembler._render_type_reference()
        for name in ("GraspCandidates", "WorldConfig", "Trajectory", "ArmState"):
            assert f"**`{name}`**" in ref

    def test_rotation_orientation_asymmetry(self, assembler):
        ref = assembler._render_type_reference()
        # Se3Pose is the canonical header (Pose is its legacy alias)...
        assert "- **`Se3Pose`** (aliases: `Pose`):" in ref
        # ...and the asymmetry the field reference exists to nail down.
        assert '`"rotation"`: Quaternion' in ref     # Se3Pose
        assert '`"orientation"`: Quaternion' in ref   # OrientedBoundingBox
        for key in ('"w"', '"x"', '"y"', '"z"'):
            assert f'`{key}`: float' in ref           # Quaternion fully expanded

    def test_nesting_and_optional_markers(self, assembler):
        ref = assembler._render_type_reference()
        # list[...] repeated fields and optional (NotRequired) fields are marked.
        assert '`"poses"`: list[Se3Pose]' in ref       # GraspCandidates.poses
        assert "(optional)" in ref                      # e.g. GraspCandidates.scores
        assert "nested dict" in ref                     # e.g. Se3Pose.position

    def test_dict_subscript_warning_and_conventions(self, assembler):
        ref = assembler._render_type_reference()
        assert "never attribute access" in ref
        assert 'pose["position"]["z"]' in ref
        # In-code conventions overlay (from gap_core.types.__doc__).
        assert "Quaternions are wxyz" in ref


class TestBuilderApi:
    def test_authoring_methods_present_with_signatures(self, assembler):
        api = assembler._render_builder_api()
        for method in (
            "add_node", "add_edge", "add_conditional_edges", "add_exit",
            "add_input", "set_exit_router", "set_outputs", "set_on_error",
        ):
            assert f"sg.{method}(" in api

    def test_signatures_are_evaluated_not_stringized(self, assembler):
        # eval_str renders real types, not `from __future__` string hints.
        api = assembler._render_builder_api()
        assert "router_field: str | None = None" in api
        assert "'str'" not in api

    def test_checkpoint_and_io_methods_excluded(self, assembler):
        # The subgraph_agent must never call add_checkpoint (checkpoint_agent's
        # job); save/load/to_dict are serialization plumbing.
        api = assembler._render_builder_api()
        assert "add_checkpoint" not in api
        assert "sg.save(" not in api
        assert "sg.load(" not in api


class TestGeneratorsGrounded:
    def test_subgraph_agent_generated_has_type_ref_and_builder_api(self, assembler):
        text = assembler.assemble_subgraph_agent(
            "detect-and-count-widgets", GENERATED_SPEC,
        ).system_prompt
        assert "Type field reference (generated" in text
        assert "Builder API (`gap.builder.Subgraph`" in text

    def test_subgraph_agent_registered_also_grounded(self, assembler):
        text = assembler.assemble_subgraph_agent(
            "perceiving-objects", REGISTERED_SPEC,
        ).system_prompt
        assert "Type field reference (generated" in text
        assert "Builder API (`gap.builder.Subgraph`" in text

    def test_coder_has_type_ref_but_not_builder_api(self, assembler):
        text = assembler.assemble_coder(CODER_SPEC).system_prompt
        assert "Type field reference (generated" in text
        # The coder writes scripts, not graphs — no builder API.
        assert "Builder API (`gap.builder.Subgraph`" not in text

    def test_old_hand_tables_removed(self, assembler):
        text = assembler.assemble_subgraph_agent(
            "detect-and-count-widgets", GENERATED_SPEC,
        ).system_prompt
        # Markers unique to the deleted hand-curated tables: the
        # _workflow_spec "Field reference" prose + both table headers.
        assert "these trip up LLMs" not in text
        assert "| Type | Keys |" not in text     # old _workflow_spec table
        assert "| Type | Shape |" not in text    # old _script_contract table
